ssh-setup/nova: Fix indefinite hang on reboot
If the normal "nova reboot" does not finish after five minutes, use the bigger
"reboot --hard" hammer. This works around reboot bugs on some architectures.

diff --git a/ssh-setup/nova b/ssh-setup/nova
--- a/ssh-setup/nova
+++ b/ssh-setup/nova
@@ -380,7 +380,13 @@ wait_reboot() {
         echo "Needs to be called with --uuid <server UUID>" >&2
         exit 1
     fi
-    nova reboot --poll "$SRVUUID"
+    if ! timeout 5m nova reboot --poll "$SRVUUID"; then
+        echo "soft reboot timed out, doing hard reboot" >&2
+        if ! nova reboot --hard --poll "$SRVUUID"; then
+            echo "hard reboot failed, aborting" >&2
+            exit 1
+        fi
+    fi
 }
 
 debug_failure() {
